// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:fleddit/src/config/environment_config.dart';
import 'package:flutter/foundation.dart'
    show TargetPlatform, defaultTargetPlatform, kIsWeb;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions web = FirebaseOptions(
    apiKey: EnvironmentConfig().firebaseWebApiKey,
    appId: '1:364982796880:web:e8dece258dbf7e6cfc4755',
    messagingSenderId: '364982796880',
    projectId: 'fleddit-2a1d7',
    authDomain: 'fleddit-2a1d7.firebaseapp.com',
    storageBucket: 'fleddit-2a1d7.appspot.com',
    measurementId: 'G-TMWWTYQV64',
  );

  static FirebaseOptions android = FirebaseOptions(
    apiKey: EnvironmentConfig().firebaseAndroidApiKey,
    appId: '1:364982796880:android:0a4343301c7e057cfc4755',
    messagingSenderId: '364982796880',
    projectId: 'fleddit-2a1d7',
    storageBucket: 'fleddit-2a1d7.appspot.com',
  );

  static FirebaseOptions ios = FirebaseOptions(
    apiKey: EnvironmentConfig().firebaseIosApiKey,
    appId: '1:364982796880:ios:e1efa2d6d4391774fc4755',
    messagingSenderId: '364982796880',
    projectId: 'fleddit-2a1d7',
    storageBucket: 'fleddit-2a1d7.appspot.com',
    iosBundleId: 'nl.freekvandeven.fleddit',
  );
}
